/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_2020();
void sub_2030();
void sub_2040();
void sub_2050();
void sub_2060();
void sub_2070();
void sub_2080();
void sub_2090();
void sub_20A0();
void sub_20B0();
void sub_20C0();
void sub_20D0();
void sub_20E0();
void sub_20F0();
void sub_2100();
void sub_2110();
void sub_2120();
void sub_2130();
void sub_2140();
void sub_2150();
void sub_2160();
void sub_2170();
void sub_2180();
void sub_2190();
void sub_21A0();
void sub_21B0();
void sub_21C0();
void sub_21D0();
void sub_21E0();
void sub_21F0();
void sub_2200();
void sub_2210();
void sub_2220();
void sub_2230();
// int _cxa_finalize(void *);
// _QWORD std::ostream::put(std::ostream *__hidden this, char); idb
// _QWORD std::chrono::_V2::system_clock::now(std::chrono::_V2::system_clock *__hidden this); idb
// __int64 GOMP_single_start(void); weak
// void *__cxa_begin_catch(void *);
// void __noreturn std::__throw_length_error(const char *); idb
// void *memset(void *s, int c, size_t n);
// __int64 __fastcall std::ostream::_M_insert<unsigned long>(_QWORD, _QWORD);
// _QWORD std::ostream::flush(std::ostream *__hidden this); idb
// __int64 GOMP_critical_end(void); weak
// __int64 GOMP_critical_start(void); weak
// _QWORD std::random_device::_M_fini(std::random_device *__hidden this); idb
// __int64 __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD); weak
// _QWORD operator new(unsigned __int64); idb
// void operator delete(void *, unsigned __int64); idb
// __int64 __fastcall omp_set_num_threads(_QWORD); weak
// __int64 __fastcall std::__ostream_insert<char,std::char_traits<char>>(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall std::ctype<char>::_M_widen_init(_QWORD); weak
// void __noreturn std::__throw_bad_cast(void); idb
// _QWORD std::random_device::_M_getval(std::random_device *__hidden this); idb
// __int64 __fastcall GOMP_parallel(_QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// __int64 __fastcall omp_get_thread_num(_QWORD); weak
// __int64 __fastcall std::ostream::_M_insert<double>(_QWORD, double); weak
// void *memmove(void *dest, const void *src, size_t n);
// void __cxa_end_catch(void);
// __int64 __fastcall omp_get_max_threads(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall std::random_device::_M_init(_QWORD, _QWORD); weak
// __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD); weak
// void _Unwind_Resume(struct _Unwind_Exception *);
// __int64 __fastcall GOMP_barrier(_QWORD); weak
// __int64 __fastcall omp_get_num_threads(_QWORD); weak
void __fastcall main_cold();
int __fastcall main(int argc, const char **argv, const char **envp);
int GLOBAL__sub_I_main();
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *deregister_tm_clones();
__int64 register_tm_clones(void); // weak
void *_do_global_dtors_aux();
__int64 frame_dummy(); // weak
__int64 __fastcall std::endl<char,std::char_traits<char>>(std::ostream *this); // idb
__int64 __fastcall std::ctype<char>::do_widen(__int64 a1, unsigned int a2);
unsigned __int64 __fastcall Benchmark::verify_sums(signed __int64 (__fastcall *a1)(signed __int64 *a1, __m128 _XMM0));
__int64 __fastcall Benchmark::openmp_critical_sum(__int64 **a1, __m128 _XMM0);
signed __int64 __fastcall Benchmark::openmp_atomic_sum(volatile signed __int64 **a1, __m128 _XMM0);
signed __int64 __fastcall Benchmark::openmp_reduction_sum(signed __int64 *a1, __m128 _XMM0);
unsigned __int64 __fastcall Benchmark::standard_vector_operation(__int64 **a1);
unsigned __int64 __fastcall Benchmark::vectorized_operation(__int64 **a1, __m128 _XMM0);
void __fastcall Benchmark::~Benchmark(Benchmark *this); // idb
void __fastcall std::_Vector_base<float>::~_Vector_base(__int64 a1);
void __fastcall std::string::_M_dispose(__int64 a1);
unsigned __int64 __fastcall Benchmark::initialize_data(Benchmark *this);
void __fastcall std::vector<float>::_M_default_append(__int64 a1, unsigned __int64 a2);
void __fastcall std::_Vector_base<int>::~_Vector_base(__int64 a1);
void __fastcall Benchmark::run_sum_benchmark(Benchmark *this, double a2, double a3, __m128 _XMM2);
void __fastcall Benchmark::run_vectorization_benchmark(Benchmark *this, double a2, double a3, __m128 _XMM2, __m128 _XMM3);
unsigned __int64 __fastcall std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::_M_gen_rand(_QWORD *a1);
unsigned __int64 __fastcall std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::operator()(_QWORD *a1);
__int64 __fastcall Benchmark::initialize_data(__int64 **a1, double a2, double a3, double a4, __m128 _XMM3, double a6, double a7, __m128 _XMM6, __m128 _XMM7);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int _cxa_atexit(void (*lpfunc)(void *), void *obj, void *lpdso_handle);
// void std::ios_base::Init::~Init(std::ios_base::Init *__hidden this); idb
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

char byte_7 = '\0'; // weak
__int16 word_12 = 62; // weak
_UNKNOWN *off_18 = &start; // weak
__int64 qword_20 = 64LL; // weak
_UNKNOWN unk_601E; // weak
_UNKNOWN unk_6038; // weak
_UNKNOWN unk_6056; // weak
_UNKNOWN unk_6071; // weak
_UNKNOWN unk_6075; // weak
_UNKNOWN unk_608D; // weak
_UNKNOWN unk_60A7; // weak
_UNKNOWN unk_60BE; // weak
_UNKNOWN unk_60D7; // weak
_UNKNOWN unk_60F3; // weak
_UNKNOWN unk_6117; // weak
_UNKNOWN unk_6133; // weak
_UNKNOWN unk_6140; // weak
_UNKNOWN unk_61A8; // weak
_UNKNOWN unk_61F0; // weak
_UNKNOWN unk_6230; // weak
_UNKNOWN unk_6250; // weak
_UNKNOWN unk_6288; // weak
_UNKNOWN unk_62C8; // weak
_UNKNOWN unk_6300; // weak
_UNKNOWN unk_6376; // weak
_UNKNOWN unk_6390; // weak
_UNKNOWN unk_63AE; // weak
_UNKNOWN unk_63C8; // weak
_UNKNOWN unk_63F8; // weak
_UNKNOWN unk_6430; // weak
_UNKNOWN unk_6458; // weak
_UNKNOWN unk_6490; // weak
_UNKNOWN unk_64BA; // weak
_UNKNOWN unk_64D2; // weak
_UNKNOWN unk_64E9; // weak
_UNKNOWN unk_64EB; // weak
_UNKNOWN unk_6507; // weak
_UNKNOWN unk_651C; // weak
_UNKNOWN unk_6533; // weak
_UNKNOWN unk_654B; // weak
_UNKNOWN unk_655D; // weak
_UNKNOWN unk_6560; // weak
_UNKNOWN unk_6573; // weak
_UNKNOWN unk_6576; // weak
void *_dso_handle = &_dso_handle; // idb
_UNKNOWN _bss_start; // weak
_QWORD std::cout[36]; // weak
_UNKNOWN std::cerr; // weak
char completed_0; // weak
_UNKNOWN std::__ioinit; // weak


//----- (0000000000002000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 93B8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000002020) ----------------------------------------------------
void sub_2020()
{
  JUMPOUT(0);
}
// 2026: control flows out of bounds to 0

//----- (0000000000002030) ----------------------------------------------------
void sub_2030()
{
  sub_2020();
}

//----- (0000000000002040) ----------------------------------------------------
void sub_2040()
{
  sub_2020();
}

//----- (0000000000002050) ----------------------------------------------------
void sub_2050()
{
  sub_2020();
}

//----- (0000000000002060) ----------------------------------------------------
void sub_2060()
{
  sub_2020();
}

//----- (0000000000002070) ----------------------------------------------------
void sub_2070()
{
  sub_2020();
}

//----- (0000000000002080) ----------------------------------------------------
void sub_2080()
{
  sub_2020();
}

//----- (0000000000002090) ----------------------------------------------------
void sub_2090()
{
  sub_2020();
}

//----- (00000000000020A0) ----------------------------------------------------
void sub_20A0()
{
  sub_2020();
}

//----- (00000000000020B0) ----------------------------------------------------
void sub_20B0()
{
  sub_2020();
}

//----- (00000000000020C0) ----------------------------------------------------
void sub_20C0()
{
  sub_2020();
}

//----- (00000000000020D0) ----------------------------------------------------
void sub_20D0()
{
  sub_2020();
}

//----- (00000000000020E0) ----------------------------------------------------
void sub_20E0()
{
  sub_2020();
}

//----- (00000000000020F0) ----------------------------------------------------
void sub_20F0()
{
  sub_2020();
}

//----- (0000000000002100) ----------------------------------------------------
void sub_2100()
{
  sub_2020();
}

//----- (0000000000002110) ----------------------------------------------------
void sub_2110()
{
  sub_2020();
}

//----- (0000000000002120) ----------------------------------------------------
void sub_2120()
{
  sub_2020();
}

//----- (0000000000002130) ----------------------------------------------------
void sub_2130()
{
  sub_2020();
}

//----- (0000000000002140) ----------------------------------------------------
void sub_2140()
{
  sub_2020();
}

//----- (0000000000002150) ----------------------------------------------------
void sub_2150()
{
  sub_2020();
}

//----- (0000000000002160) ----------------------------------------------------
void sub_2160()
{
  sub_2020();
}

//----- (0000000000002170) ----------------------------------------------------
void sub_2170()
{
  sub_2020();
}

//----- (0000000000002180) ----------------------------------------------------
void sub_2180()
{
  sub_2020();
}

//----- (0000000000002190) ----------------------------------------------------
void sub_2190()
{
  sub_2020();
}

//----- (00000000000021A0) ----------------------------------------------------
void sub_21A0()
{
  sub_2020();
}

//----- (00000000000021B0) ----------------------------------------------------
void sub_21B0()
{
  sub_2020();
}

//----- (00000000000021C0) ----------------------------------------------------
void sub_21C0()
{
  sub_2020();
}

//----- (00000000000021D0) ----------------------------------------------------
void sub_21D0()
{
  sub_2020();
}

//----- (00000000000021E0) ----------------------------------------------------
void sub_21E0()
{
  sub_2020();
}

//----- (00000000000021F0) ----------------------------------------------------
void sub_21F0()
{
  sub_2020();
}

//----- (0000000000002200) ----------------------------------------------------
void sub_2200()
{
  sub_2020();
}

//----- (0000000000002210) ----------------------------------------------------
void sub_2210()
{
  sub_2020();
}

//----- (0000000000002220) ----------------------------------------------------
void sub_2220()
{
  sub_2020();
}

//----- (0000000000002230) ----------------------------------------------------
void sub_2230()
{
  sub_2020();
}

//----- (0000000000002460) ----------------------------------------------------
void __fastcall main_cold()
{
  struct _Unwind_Exception *v0; // rbx
  __int64 v1; // rbp
  Benchmark *v2; // r12
  void *v3; // rbp
  __int64 v4; // r12
  __int64 v5; // rax
  std::ostream *v6; // rax

  __asm { vzeroupper }
  Benchmark::~Benchmark(v2);
  if ( v1 == 1 )
  {
    v3 = __cxa_begin_catch(v0);
    v4 = std::operator<<<std::char_traits<char>>(&std::cerr, &unk_6576);
    v5 = (*(__int64 (__fastcall **)(void *))(*(_QWORD *)v3 + 16LL))(v3);
    v6 = (std::ostream *)std::operator<<<std::char_traits<char>>(v4, v5);
    std::endl<char,std::char_traits<char>>(v6);
    __cxa_end_catch();
    JUMPOUT(0x278B);
  }
  _Unwind_Resume(v0);
}
// 24C0: control flows out of bounds to 278B
// 2466: variable 'v2' is possibly undefined
// 2475: variable 'v1' is possibly undefined
// 247B: variable 'v0' is possibly undefined
// 2310: using guessed type __int64 __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD);

//----- (0000000000002520) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  double v3; // xmm0_8
  double v4; // xmm1_8
  __m128 v5; // xmm2
  __m128 v6; // xmm3
  __int64 v7; // rax
  __int64 v8; // rax
  _QWORD *v9; // rax
  _QWORD *v10; // rbx
  _DWORD *v11; // rax
  _DWORD *v12; // rbx
  _DWORD *v13; // rax
  _DWORD *v14; // rbx
  __int64 v15; // rax
  __int64 v16; // rax
  __int64 v17; // rax
  __int64 v18; // rax
  __int64 v19; // r13
  __int64 v20; // rdx
  __int64 v21; // rcx
  __int64 v22; // r8
  __int64 v23; // r9
  unsigned int max_threads; // eax
  __int64 v25; // rax
  __int64 v26; // rax
  __int64 v27; // rax
  _QWORD *v29; // [rsp+0h] [rbp-78h] BYREF
  _QWORD *v30; // [rsp+8h] [rbp-70h]
  _QWORD *v31; // [rsp+10h] [rbp-68h]
  _DWORD *v32; // [rsp+18h] [rbp-60h]
  _DWORD *v33; // [rsp+20h] [rbp-58h]
  _DWORD *v34; // [rsp+28h] [rbp-50h]
  _DWORD *v35; // [rsp+30h] [rbp-48h]
  _DWORD *v36; // [rsp+38h] [rbp-40h]
  _DWORD *v37; // [rsp+40h] [rbp-38h]
  unsigned __int64 v38; // [rsp+48h] [rbp-30h]

  v38 = __readfsqword(0x28u);
  std::operator<<<std::char_traits<char>>(std::cout, &unk_63C8);
  v7 = std::operator<<<std::char_traits<char>>(std::cout, &unk_64BA);
  v8 = std::ostream::operator<<(v7, 3);
  std::operator<<<std::char_traits<char>>(v8, &unk_64D2);
  v30 = 0;
  v9 = (_QWORD *)operator new(0x2FAF0800u);
  v10 = v9 + 100000000;
  v29 = v9;
  v31 = v9 + 100000000;
  *v9 = 0;
  if ( v9 + 1 != v9 + 100000000 )
    memset(v9 + 1, 0, 0x2FAF07F8u);
  v30 = v10;
  v33 = 0;
  v11 = (_DWORD *)operator new(0x17D78400u);
  v12 = v11 + 100000000;
  v32 = v11;
  v34 = v11 + 100000000;
  *v11 = 0;
  if ( v11 + 1 != v11 + 100000000 )
    memset(v11 + 1, 0, 0x17D783FCu);
  v33 = v12;
  v36 = 0;
  v13 = (_DWORD *)operator new(0x17D78400u);
  v14 = v13 + 100000000;
  v35 = v13;
  v37 = v13 + 100000000;
  *v13 = 0;
  if ( v13 + 1 != v13 + 100000000 )
    memset(v13 + 1, 0, 0x17D783FCu);
  v36 = v14;
  Benchmark::initialize_data((Benchmark *)&v29);
  std::operator<<<std::char_traits<char>>(std::cout, &unk_63F8);
  v15 = std::operator<<<std::char_traits<char>>(std::cout, &unk_64EB);
  v16 = std::ostream::_M_insert<unsigned long>(v15, 100000000);
  std::operator<<<std::char_traits<char>>(v16, &unk_6507);
  v17 = std::operator<<<std::char_traits<char>>(std::cout, &unk_651C);
  v18 = std::ostream::operator<<(v17, 3);
  std::operator<<<std::char_traits<char>>(v18, &unk_6430);
  v19 = std::operator<<<std::char_traits<char>>(std::cout, &unk_6533);
  max_threads = omp_get_max_threads(std::cout, &unk_6533, v20, v21, v22, v23, v29);
  v25 = std::ostream::operator<<(v19, max_threads);
  std::operator<<<std::char_traits<char>>(v25, &unk_654B);
  std::operator<<<std::char_traits<char>>(std::cout, &unk_6458);
  v26 = std::operator<<<std::char_traits<char>>(std::cout, &unk_6560);
  v27 = std::ostream::operator<<(v26, 201511);
  std::operator<<<std::char_traits<char>>(v27, &unk_64E9);
  std::endl<char,std::char_traits<char>>((std::ostream *)std::cout);
  Benchmark::run_sum_benchmark((Benchmark *)&v29, v3, v4, v5);
  Benchmark::run_vectorization_benchmark((Benchmark *)&v29, v3, v4, v5, v6);
  Benchmark::~Benchmark((Benchmark *)&v29);
  std::operator<<<std::char_traits<char>>(std::cout, &unk_6490);
  return 0;
}
// 27FA: control flows out of bounds to 2471
// 2702: variable 'v20' is possibly undefined
// 2702: variable 'v21' is possibly undefined
// 2702: variable 'v22' is possibly undefined
// 2702: variable 'v23' is possibly undefined
// 2765: variable 'v3' is possibly undefined
// 2765: variable 'v4' is possibly undefined
// 2765: variable 'v5' is possibly undefined
// 276D: variable 'v6' is possibly undefined
// 2310: using guessed type __int64 __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD);
// 2400: using guessed type __int64 __fastcall omp_get_max_threads(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 2420: using guessed type __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 9040: using guessed type _QWORD std::cout[36];

//----- (0000000000002800) ----------------------------------------------------
int GLOBAL__sub_I_main()
{
  std::ios_base::Init::Init((std::ios_base::Init *)&std::__ioinit);
  return _cxa_atexit((void (*)(void *))&std::ios_base::Init::~Init, &std::__ioinit, &_dso_handle);
}

//----- (0000000000002830) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 283A: positive sp value 8 has been found
// 2841: variable 'v3' is possibly undefined

//----- (0000000000002860) ----------------------------------------------------
void *deregister_tm_clones()
{
  return &_bss_start;
}

//----- (0000000000002890) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}
// 2890: using guessed type __int64 register_tm_clones();

//----- (00000000000028D0) ----------------------------------------------------
void *_do_global_dtors_aux()
{
  void *result; // rax

  if ( !completed_0 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 9270: using guessed type char completed_0;

//----- (0000000000002910) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 2890: using guessed type __int64 register_tm_clones(void);
// 2910: using guessed type __int64 frame_dummy();

//----- (0000000000002920) ----------------------------------------------------
__int64 __fastcall std::endl<char,std::char_traits<char>>(std::ostream *this)
{
  __int64 v1; // rax
  _BYTE *v2; // r12
  char v3; // si
  std::ostream *v4; // rax
  __int64 (__fastcall *v6)(__int64, unsigned int); // rax

  v1 = *(_QWORD *)(*(_QWORD *)this - 24LL);
  v2 = *(_BYTE **)((char *)this + v1 + 240);
  if ( !v2 )
    std::__throw_bad_cast();
  if ( v2[56] )
  {
    v3 = v2[67];
  }
  else
  {
    std::ctype<char>::_M_widen_init(*(_QWORD *)((char *)this + v1 + 240));
    v3 = 10;
    v6 = *(__int64 (__fastcall **)(__int64, unsigned int))(*(_QWORD *)v2 + 48LL);
    if ( v6 != std::ctype<char>::do_widen )
      v3 = v6((__int64)v2, 10u);
  }
  v4 = (std::ostream *)std::ostream::put(this, v3);
  return std::ostream::flush(v4);
}
// 2370: using guessed type __int64 __fastcall std::ctype<char>::_M_widen_init(_QWORD);

//----- (00000000000029A0) ----------------------------------------------------
__int64 __fastcall std::ctype<char>::do_widen(__int64 a1, unsigned int a2)
{
  return a2;
}

//----- (00000000000029B0) ----------------------------------------------------
unsigned __int64 __fastcall Benchmark::verify_sums(signed __int64 (__fastcall *a1)(signed __int64 *a1, __m128 _XMM0))
{
  __int64 v2; // rbp
  __int64 v7; // [rsp+8h] [rbp-40h] BYREF
  __int64 v8; // [rsp+10h] [rbp-38h] BYREF
  __int64 *v9; // [rsp+18h] [rbp-30h]
  unsigned __int64 v10; // [rsp+28h] [rbp-20h]

  _RBX = a1;
  v2 = *(_QWORD *)a1;
  v10 = __readfsqword(0x28u);
  if ( !(unsigned __int8)GOMP_single_start() )
  {
    GOMP_barrier(a1);
    if ( !(unsigned __int8)GOMP_single_start() )
      goto LABEL_3;
LABEL_6:
    v8 = v2;
    v9 = &v7;
    v7 = 0;
    GOMP_parallel(Benchmark::openmp_atomic_sum, &v8, 0, 0);
    __asm
    {
      vmovsd  xmm0, [rsp+48h+var_40]
      vmovsd  qword ptr [rbx+10h], xmm0
    }
    GOMP_barrier(Benchmark::openmp_atomic_sum);
    if ( !(unsigned __int8)GOMP_single_start() )
      return v10 - __readfsqword(0x28u);
LABEL_7:
    v8 = v2;
    v9 = 0;
    GOMP_parallel(Benchmark::openmp_critical_sum, &v8, 0, 0);
    __asm
    {
      vmovsd  xmm0, [rsp+48h+var_30]
      vmovsd  qword ptr [rbx+18h], xmm0
    }
    return v10 - __readfsqword(0x28u);
  }
  v8 = v2;
  v9 = 0;
  a1 = Benchmark::openmp_reduction_sum;
  GOMP_parallel(Benchmark::openmp_reduction_sum, &v8, 0, 0);
  __asm
  {
    vmovsd  xmm0, [rsp+48h+var_30]
    vmovsd  qword ptr [rbx+8], xmm0
  }
  GOMP_barrier(Benchmark::openmp_reduction_sum);
  if ( (unsigned __int8)GOMP_single_start() )
    goto LABEL_6;
LABEL_3:
  GOMP_barrier(a1);
  if ( (unsigned __int8)GOMP_single_start() )
    goto LABEL_7;
  return v10 - __readfsqword(0x28u);
}
// 2270: using guessed type __int64 GOMP_single_start(void);
// 23A0: using guessed type __int64 __fastcall GOMP_parallel(_QWORD, _QWORD, _QWORD, _QWORD);
// 2440: using guessed type __int64 __fastcall GOMP_barrier(_QWORD);

//----- (0000000000002AE0) ----------------------------------------------------
__int64 __fastcall Benchmark::openmp_critical_sum(__int64 **a1, __m128 _XMM0)
{
  __int64 v3; // r13
  unsigned __int64 v4; // rbx
  unsigned __int64 num_threads; // rsi
  unsigned __int64 thread_num; // rcx
  unsigned __int64 v7; // rax
  unsigned __int64 v8; // rdx
  unsigned __int64 v10; // rdx
  unsigned __int64 v11; // rax
  __int64 v12; // rdx
  __int64 v13; // rax

  _R12 = a1;
  v3 = **a1;
  if ( ((*a1)[1] - v3) >> 3 )
  {
    v4 = ((*a1)[1] - v3) >> 3;
    num_threads = (int)omp_get_num_threads();
    thread_num = (int)omp_get_thread_num();
    v7 = v4 / num_threads;
    v8 = v4 % num_threads;
    if ( thread_num < v4 % num_threads )
    {
      ++v7;
      v8 = 0;
    }
    __asm { vxorpd  xmm0, xmm0, xmm0 }
    v10 = v7 * thread_num + v8;
    v11 = v10 + v7;
    if ( v10 < v11 )
    {
      v12 = v3 + 8 * v10;
      v13 = v3 + 8 * v11;
      do
      {
        __asm { vaddsd  xmm0, xmm0, qword ptr [rdx] }
        v12 += 8;
      }
      while ( v12 != v13 );
    }
  }
  else
  {
    __asm { vxorpd  xmm0, xmm0, xmm0 }
  }
  __asm { vmovsd  [rsp+38h+var_30], xmm0 }
  GOMP_barrier();
  GOMP_critical_start();
  __asm
  {
    vmovsd  xmm0, [rsp+38h+var_30]
    vaddsd  xmm0, xmm0, qword ptr [r12+8]
    vmovsd  qword ptr [r12+8], xmm0
  }
  return GOMP_critical_end();
}
// 22D0: using guessed type __int64 GOMP_critical_end(void);
// 22F0: using guessed type __int64 GOMP_critical_start(void);
// 23C0: using guessed type __int64 omp_get_thread_num(void);
// 2440: using guessed type __int64 GOMP_barrier(void);
// 2450: using guessed type __int64 omp_get_num_threads(void);

//----- (0000000000002BA0) ----------------------------------------------------
signed __int64 __fastcall Benchmark::openmp_atomic_sum(volatile signed __int64 **a1, __m128 _XMM0)
{
  volatile signed __int64 v2; // r13
  unsigned __int64 v3; // rbp
  unsigned __int64 num_threads; // rsi
  unsigned __int64 thread_num; // rcx
  unsigned __int64 v6; // rax
  unsigned __int64 v7; // rdx
  unsigned __int64 v9; // rdx
  unsigned __int64 v10; // rax
  volatile signed __int64 *v11; // rcx
  signed __int64 result; // rax
  unsigned __int64 v18; // rdx
  unsigned __int64 v19; // rax

  v2 = **a1;
  if ( (*((_QWORD *)*a1 + 1) - v2) >> 3 )
  {
    v3 = (*((_QWORD *)*a1 + 1) - v2) >> 3;
    num_threads = (int)omp_get_num_threads();
    thread_num = (int)omp_get_thread_num();
    v6 = v3 / num_threads;
    v7 = v3 % num_threads;
    if ( thread_num < v3 % num_threads )
    {
      ++v6;
      v7 = 0;
    }
    __asm { vxorpd  xmm0, xmm0, xmm0 }
    v9 = v6 * thread_num + v7;
    v10 = v9 + v6;
    if ( v9 < v10 )
    {
      v18 = v2 + 8 * v9;
      v19 = v2 + 8 * v10;
      do
      {
        __asm { vaddsd  xmm0, xmm0, qword ptr [rdx] }
        v18 += 8LL;
      }
      while ( v19 != v18 );
    }
  }
  else
  {
    __asm { vxorpd  xmm0, xmm0, xmm0 }
  }
  __asm { vmovsd  [rsp+38h+var_30], xmm0 }
  GOMP_barrier();
  v11 = a1[1];
  _RDX = *v11;
  __asm { vmovsd  xmm0, [rsp+38h+var_30] }
  while ( 1 )
  {
    __asm { vmovq   xmm2, rdx }
    __asm
    {
      vaddsd  xmm1, xmm0, xmm2
      vmovq   rsi, xmm1
    }
    result = _InterlockedCompareExchange64(v11, _RSI, _RDX);
    if ( _RDX == result )
      break;
    _RDX = result;
  }
  return result;
}
// 23C0: using guessed type __int64 omp_get_thread_num(void);
// 2440: using guessed type __int64 GOMP_barrier(void);
// 2450: using guessed type __int64 omp_get_num_threads(void);

//----- (0000000000002C80) ----------------------------------------------------
signed __int64 __fastcall Benchmark::openmp_reduction_sum(signed __int64 *a1, __m128 _XMM0)
{
  __int64 v2; // r13
  unsigned __int64 v3; // rbx
  int num_threads; // ebp
  unsigned __int64 thread_num; // rcx
  unsigned __int64 v6; // rax
  unsigned __int64 v7; // rdx
  unsigned __int64 v9; // rdx
  unsigned __int64 v10; // rax
  signed __int64 result; // rax
  __int64 v16; // rdx
  __int64 v17; // rax

  v2 = *(_QWORD *)*a1;
  if ( (*(_QWORD *)(*a1 + 8) - v2) >> 3 )
  {
    v3 = (*(_QWORD *)(*a1 + 8) - v2) >> 3;
    num_threads = omp_get_num_threads();
    thread_num = (int)omp_get_thread_num();
    v6 = v3 / num_threads;
    v7 = v3 % num_threads;
    if ( thread_num < v7 )
    {
      ++v6;
      v7 = 0;
    }
    __asm { vxorpd  xmm0, xmm0, xmm0 }
    v9 = v6 * thread_num + v7;
    v10 = v9 + v6;
    if ( v9 < v10 )
    {
      v16 = v2 + 8 * v9;
      v17 = v2 + 8 * v10;
      do
      {
        __asm { vaddsd  xmm0, xmm0, qword ptr [rdx] }
        v16 += 8;
      }
      while ( v17 != v16 );
    }
  }
  else
  {
    __asm { vxorpd  xmm0, xmm0, xmm0 }
  }
  for ( _RDX = a1[1]; ; _RDX = result )
  {
    __asm { vmovq   xmm2, rdx }
    __asm
    {
      vaddsd  xmm1, xmm0, xmm2
      vmovq   rsi, xmm1
    }
    result = _InterlockedCompareExchange64(a1 + 1, _RSI, _RDX);
    if ( _RDX == result )
      break;
  }
  return result;
}
// 23C0: using guessed type __int64 omp_get_thread_num(void);
// 2450: using guessed type __int64 omp_get_num_threads(void);

//----- (0000000000002D50) ----------------------------------------------------
unsigned __int64 __fastcall Benchmark::standard_vector_operation(__int64 **a1)
{
  __int64 *v1; // r14
  unsigned __int64 result; // rax
  unsigned __int64 v4; // rbx
  int num_threads; // r12d
  unsigned __int64 thread_num; // rcx
  unsigned __int64 v7; // rax
  unsigned __int64 v8; // rdx

  v1 = a1[1];
  _RBP = v1[3];
  result = (v1[4] - _RBP) >> 2;
  if ( result )
  {
    v4 = (v1[4] - _RBP) >> 2;
    num_threads = omp_get_num_threads();
    thread_num = (int)omp_get_thread_num();
    v7 = v4 / num_threads;
    v8 = v4 % num_threads;
    if ( thread_num < v8 )
    {
      ++v7;
      v8 = 0;
    }
    _RDX = v7 * thread_num + v8;
    result = _RDX + v7;
    if ( _RDX < result )
    {
      _RSI = v1[6];
      __asm { vmovss  xmm4, dword ptr cs:ymmword_65A0 }
      _RCX = **a1;
      do
      {
        __asm
        {
          vmovss  xmm2, dword ptr [rbp+rdx*4+0]
          vmovss  xmm1, dword ptr [rsi+rdx*4]
          vmulss  xmm0, xmm2, xmm1
          vaddss  xmm3, xmm2, xmm1
          vmulss  xmm0, xmm0, xmm3
          vsubss  xmm0, xmm0, xmm2
          vaddss  xmm0, xmm0, xmm1
          vaddss  xmm0, xmm0, xmm0
          vaddss  xmm0, xmm0, xmm4
          vmovss  dword ptr [rcx+rdx*4], xmm0
        }
        ++_RDX;
      }
      while ( result != _RDX );
    }
  }
  return result;
}
// 23C0: using guessed type __int64 omp_get_thread_num(void);
// 2450: using guessed type __int64 omp_get_num_threads(void);

//----- (0000000000002E10) ----------------------------------------------------
unsigned __int64 __fastcall Benchmark::vectorized_operation(__int64 **a1, __m128 _XMM0)
{
  __int64 *v4; // r15
  unsigned __int64 result; // rax
  unsigned __int64 v7; // rbx
  unsigned __int64 num_threads; // r13
  unsigned __int64 thread_num; // rcx
  unsigned __int64 v10; // rdx
  unsigned __int64 v11; // rdx
  unsigned __int64 v12; // r8
  unsigned __int64 v31; // rsi
  unsigned __int64 v33; // r13

  v4 = a1[1];
  _R12 = v4[3];
  result = (v4[4] - _R12) >> 2;
  if ( result )
  {
    v7 = (v4[4] - _R12) >> 2;
    num_threads = (int)omp_get_num_threads();
    thread_num = (int)omp_get_thread_num();
    result = v7 / num_threads;
    v10 = v7 % num_threads;
    if ( thread_num < v7 % num_threads )
    {
      ++result;
      v10 = 0;
    }
    v11 = result * thread_num + v10;
    v12 = result + v11;
    if ( v11 < result + v11 )
    {
      _R10 = v4[6];
      _R9 = **a1;
      if ( result - 1 <= 6 )
      {
        _RCX = v11;
        v31 = 0;
      }
      else
      {
        __asm { vmovaps ymm4, cs:ymmword_65A0 }
        _RCX = 0;
        _R11 = _R12 + 4 * v11;
        _RDI = _R10 + 4 * v11;
        _RSI = _R9 + 4 * v11;
        do
        {
          __asm
          {
            vmovups xmm5, xmmword ptr [r11+rcx]
            vinsertf128 ymm2, ymm5, xmmword ptr [r11+rcx+10h], 1
            vmovups xmm6, xmmword ptr [rdi+rcx]
            vinsertf128 ymm1, ymm6, xmmword ptr [rdi+rcx+10h], 1
            vaddps  ymm3, ymm2, ymm1
            vmulps  ymm0, ymm2, ymm1
            vmulps  ymm0, ymm0, ymm3
            vsubps  ymm0, ymm0, ymm2
            vaddps  ymm0, ymm0, ymm1
            vaddps  ymm0, ymm0, ymm0
            vaddps  ymm0, ymm0, ymm4
            vmovups xmmword ptr [rsi+rcx], xmm0
            vextractf128 xmmword ptr [rsi+rcx+10h], ymm0, 1
          }
          _RCX += 32;
        }
        while ( 32 * (result >> 3) != _RCX );
        v31 = result & 0xFFFFFFFFFFFFFFF8LL;
        _RCX = (result & 0xFFFFFFFFFFFFFFF8LL) + v11;
        if ( result == (result & 0xFFFFFFFFFFFFFFF8LL) )
        {
          __asm { vzeroupper }
          return result;
        }
        __asm { vzeroupper }
      }
      v33 = result - 1 - v31;
      result -= v31;
      if ( v33 <= 2 )
        goto LABEL_12;
      _RDX = v31 + v11;
      __asm
      {
        vmovups xmm2, xmmword ptr [r12+rdx*4]
        vmovups xmm1, xmmword ptr [r10+rdx*4]
        vmulps  xmm0, xmm2, xmm1
        vaddps  xmm3, xmm2, xmm1
        vmulps  xmm0, xmm0, xmm3
        vsubps  xmm0, xmm0, xmm2
        vaddps  xmm0, xmm0, xmm1
        vaddps  xmm0, xmm0, xmm0
        vaddps  xmm0, xmm0, xmmword ptr cs:ymmword_65A0
        vmovups xmmword ptr [r9+rdx*4], xmm0
      }
      _RCX += result & 0xFFFFFFFFFFFFFFFCLL;
      if ( result != (result & 0xFFFFFFFFFFFFFFFCLL) )
      {
LABEL_12:
        __asm { vmovss  xmm4, dword ptr cs:ymmword_65A0 }
        do
        {
          __asm
          {
            vmovss  xmm2, dword ptr [r12+rcx*4]
            vmovss  xmm1, dword ptr [r10+rcx*4]
            vmulss  xmm0, xmm2, xmm1
            vaddss  xmm3, xmm2, xmm1
            vmulss  xmm0, xmm0, xmm3
            vsubss  xmm0, xmm0, xmm2
            vaddss  xmm0, xmm0, xmm1
            vaddss  xmm0, xmm0, xmm0
            vaddss  xmm0, xmm0, xmm4
            vmovss  dword ptr [r9+rcx*4], xmm0
          }
          ++_RCX;
        }
        while ( v12 > _RCX );
      }
    }
  }
  return result;
}
// 23C0: using guessed type __int64 omp_get_thread_num(void);
// 2450: using guessed type __int64 omp_get_num_threads(void);

//----- (0000000000003000) ----------------------------------------------------
void __fastcall Benchmark::~Benchmark(Benchmark *this)
{
  void *v2; // rdi
  void *v3; // rdi

  v2 = (void *)*((_QWORD *)this + 6);
  if ( v2 )
    operator delete(v2, *((_QWORD *)this + 8) - (_QWORD)v2);
  v3 = (void *)*((_QWORD *)this + 3);
  if ( v3 )
    operator delete(v3, *((_QWORD *)this + 5) - (_QWORD)v3);
  if ( *(_QWORD *)this )
    operator delete(*(void **)this, *((_QWORD *)this + 2) - *(_QWORD *)this);
}

//----- (0000000000003060) ----------------------------------------------------
void __fastcall std::_Vector_base<float>::~_Vector_base(__int64 a1)
{
  if ( *(_QWORD *)a1 )
    operator delete(*(void **)a1, *(_QWORD *)(a1 + 16) - *(_QWORD *)a1);
}

//----- (0000000000003090) ----------------------------------------------------
void __fastcall std::string::_M_dispose(__int64 a1)
{
  if ( *(_QWORD *)a1 != a1 + 16 )
    operator delete(*(void **)a1, *(_QWORD *)(a1 + 16) + 1LL);
}

//----- (00000000000030C0) ----------------------------------------------------
unsigned __int64 __fastcall Benchmark::initialize_data(Benchmark *this)
{
  unsigned __int64 v1; // rcx
  __int64 v2; // rdx
  __int64 v4; // [rsp+8h] [rbp-2780h] BYREF
  _QWORD v5[2]; // [rsp+10h] [rbp-2778h] BYREF
  _QWORD v6[4]; // [rsp+20h] [rbp-2768h] BYREF
  _BYTE v7[1832]; // [rsp+40h] [rbp-2748h] BYREF
  void *v8[2]; // [rsp+13D0h] [rbp-13B8h] BYREF
  _QWORD v9[623]; // [rsp+13E0h] [rbp-13A8h] BYREF
  unsigned __int64 v10; // [rsp+2758h] [rbp-30h]

  v10 = __readfsqword(0x28u);
  v9[0] = 0x746C7561666564LL;
  v8[0] = v9;
  v8[1] = &byte_7;
  std::random_device::_M_init(v7, v8);
  if ( v8[0] != v9 )
    operator delete(v8[0], v9[0] + 1LL);
  v1 = (unsigned int)std::random_device::_M_getval((std::random_device *)v7);
  v2 = 1;
  v8[0] = (void *)v1;
  while ( 1 )
  {
    v8[v2] = (void *)((unsigned int)v2 + 1812433253 * ((unsigned int)v1 ^ (unsigned int)(v1 >> 30)));
    if ( ++v2 == 624 )
      break;
    v1 = (unsigned __int64)v8[v2 - 1];
  }
  v6[0] = this;
  v6[1] = v8;
  v5[0] = 0;
  v9[622] = 624;
  v5[1] = 0x4059000000000000LL;
  v4 = 0x4120000000000000LL;
  v6[2] = v5;
  v6[3] = &v4;
  GOMP_parallel(Benchmark::initialize_data, v6, 0, 0);
  std::random_device::_M_fini((std::random_device *)v7);
  return v10 - __readfsqword(0x28u);
}
// 7: using guessed type char;
// 23A0: using guessed type __int64 __fastcall GOMP_parallel(_QWORD, _QWORD, _QWORD, _QWORD);
// 2410: using guessed type __int64 __fastcall std::random_device::_M_init(_QWORD, _QWORD);

//----- (0000000000003290) ----------------------------------------------------
void __fastcall std::vector<float>::_M_default_append(__int64 a1, unsigned __int64 a2)
{
  _DWORD *v3; // rdx
  void *v4; // r15
  __int64 v5; // rbp
  unsigned __int64 v6; // r13
  __int64 v7; // rax
  bool v8; // cf
  unsigned __int64 v9; // rax
  signed __int64 v10; // r8
  char *v11; // r14
  char *v12; // rbp
  char *v13; // rcx
  unsigned __int64 v14; // rsi
  char *v15; // rax
  unsigned __int64 v16; // [rsp+0h] [rbp-48h]
  unsigned __int64 v17; // [rsp+0h] [rbp-48h]
  signed __int64 v18; // [rsp+8h] [rbp-40h]

  if ( a2 )
  {
    v3 = *(_DWORD **)(a1 + 8);
    v4 = *(void **)a1;
    v5 = (__int64)v3 - *(_QWORD *)a1;
    v6 = v5 >> 2;
    if ( a2 > (__int64)(*(_QWORD *)(a1 + 16) - (_QWORD)v3) >> 2 )
    {
      if ( 0x1FFFFFFFFFFFFFFFLL - v6 < a2 )
        std::__throw_length_error("vector::_M_default_append");
      v7 = (__int64)(*(_QWORD *)(a1 + 8) - *(_QWORD *)a1) >> 2;
      if ( a2 >= v6 )
        v7 = a2;
      v8 = __CFADD__(v6, v7);
      v9 = v6 + v7;
      if ( v8 )
      {
        v17 = 0x7FFFFFFFFFFFFFFCLL;
        v15 = (char *)operator new(0x7FFFFFFFFFFFFFFCuLL);
      }
      else
      {
        if ( !v9 )
        {
          v10 = *(_QWORD *)(a1 + 8) - *(_QWORD *)a1;
          v16 = 0;
          v11 = 0;
          goto LABEL_9;
        }
        if ( v9 > 0x1FFFFFFFFFFFFFFFLL )
          v9 = 0x1FFFFFFFFFFFFFFFLL;
        v17 = 4 * v9;
        v15 = (char *)operator new(4 * v9);
      }
      v4 = *(void **)a1;
      v11 = v15;
      v16 = (unsigned __int64)&v15[v17];
      v10 = *(_QWORD *)(a1 + 8) - *(_QWORD *)a1;
LABEL_9:
      v12 = &v11[v5];
      *(_DWORD *)v12 = 0;
      if ( a2 != 1 )
      {
        v18 = v10;
        memset(v12 + 4, 0, 4 * (a2 - 1));
        v10 = v18;
      }
      if ( v10 > 0 )
      {
        memmove(v11, v4, v10);
        v14 = *(_QWORD *)(a1 + 16) - (_QWORD)v4;
      }
      else
      {
        if ( !v4 )
        {
LABEL_13:
          *(_QWORD *)a1 = v11;
          *(_QWORD *)(a1 + 8) = &v11[4 * v6 + 4 * a2];
          *(_QWORD *)(a1 + 16) = v16;
          return;
        }
        v14 = *(_QWORD *)(a1 + 16) - (_QWORD)v4;
      }
      operator delete(v4, v14);
      goto LABEL_13;
    }
    *v3 = 0;
    v13 = (char *)(v3 + 1);
    if ( a2 != 1 )
      v13 = (char *)memset(v3 + 1, 0, 4 * (a2 - 1)) + 4 * a2 - 4;
    *(_QWORD *)(a1 + 8) = v13;
  }
}

//----- (0000000000003470) ----------------------------------------------------
void __fastcall std::_Vector_base<int>::~_Vector_base(__int64 a1)
{
  if ( *(_QWORD *)a1 )
    operator delete(*(void **)a1, *(_QWORD *)(a1 + 16) - *(_QWORD *)a1);
}

//----- (00000000000034A0) ----------------------------------------------------
void __fastcall Benchmark::run_sum_benchmark(Benchmark *this, double a2, double a3, __m128 _XMM2)
{
  __int64 v6; // rdx
  __int64 v7; // rax
  char v12; // cf
  char v13; // zf
  __int64 v33; // rdx
  void *v34; // rsi
  __int64 v35; // rax
  _BYTE *v36; // rbp
  char v37; // si
  std::ostream *v38; // rax
  __int64 v39; // rax
  int *v42; // rcx
  __int64 v43; // rax
  int v46; // r12d
  __int64 v48; // rdx
  __int64 j; // rax
  _QWORD *v57; // rdi
  signed __int64 (__fastcall *v58)(signed __int64 *, __m128); // rdi
  int v61; // r13d
  _QWORD *v69; // rdi
  signed __int64 (__fastcall *v70)(volatile signed __int64 **, __m128); // rdi
  int v73; // ebp
  _QWORD *v80; // rdi
  __int64 (__fastcall *v81)(__int64 **, __m128); // rdi
  int v84; // r13d
  _QWORD *v90; // rdi
  int v91; // ecx
  __int64 v93; // r12
  std::ostream *v96; // rbp
  __int64 v97; // rax
  _BYTE *v98; // r12
  char v99; // si
  std::ostream *v100; // rax
  __int64 v105; // rax
  __int64 v111; // rbp
  __int64 v113; // rbp
  __int64 v115; // rbp
  __int64 v117; // rbp
  __int64 v120; // rax
  __int64 v121; // rbp
  __int64 v123; // rbp
  __int64 v125; // rbp
  __int64 v127; // rbp
  __int64 v130; // rax
  __int64 v131; // rbp
  __int64 v134; // rbp
  __int64 v136; // rbp
  __int64 v138; // rbp
  __int64 v141; // rax
  __int64 v142; // rbp
  __int64 v144; // rbp
  __int64 v146; // rbp
  __int64 v148; // rbp
  __int64 v151; // rax
  __int64 (__fastcall *v152)(__int64, unsigned int); // rax
  __int64 v155; // r12
  std::ostream *v158; // r13
  __int64 v159; // rax
  _BYTE *v160; // r12
  char v162; // si
  std::ostream *v163; // rax
  __int64 v167; // r12
  std::ostream *v171; // rbp
  __int64 v174; // rax
  _BYTE *v175; // r12
  char v176; // si
  std::ostream *v177; // rax
  __int64 (__fastcall *v178)(__int64, unsigned int); // rax
  char v179; // al
  __int64 (__fastcall *v180)(__int64, unsigned int); // rax
  __int64 (__fastcall *v181)(__int64, unsigned int); // rax
  char v182; // al
  int i; // [rsp+3Ch] [rbp-DCh]
  int *v223; // [rsp+40h] [rbp-D8h]
  int *v226; // [rsp+58h] [rbp-C0h]
  void *v227; // [rsp+60h] [rbp-B8h]
  __int64 v228; // [rsp+78h] [rbp-A0h] BYREF
  Benchmark *v229; // [rsp+80h] [rbp-98h] BYREF
  __int64 *v230; // [rsp+88h] [rbp-90h]
  Benchmark *v231; // [rsp+90h] [rbp-88h] BYREF
  int *v232; // [rsp+98h] [rbp-80h]
  int *v233; // [rsp+A0h] [rbp-78h]
  __int64 v234; // [rsp+A8h] [rbp-70h]
  void *v235; // [rsp+B0h] [rbp-68h]
  __int64 v236; // [rsp+B8h] [rbp-60h]
  _QWORD v237[11]; // [rsp+C0h] [rbp-58h] BYREF

  v237[3] = __readfsqword(0x28u);
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6140, 62);
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, "=================================\n", 34);
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_61A8, 70);
  v6 = *((_QWORD *)this + 1);
  v7 = *(_QWORD *)this;
  if ( v6 == *(_QWORD *)this )
  {
    __asm
    {
      vxorpd  xmm2, xmm2, xmm2
      vmovq   xmm3, cs:qword_6630
      vmovsd  xmm1, xmm2, xmm2
      vmovsd  xmm0, xmm2, xmm2
      vmovsd  [rsp+118h+var_F0], xmm2
    }
  }
  else
  {
    __asm
    {
      vxorpd  xmm4, xmm4, xmm4
      vmovsd  [rsp+118h+var_F0], xmm4
      vmovsd  xmm0, xmm4, xmm4
    }
    do
    {
      __asm { vaddsd  xmm0, xmm0, qword ptr [rax] }
      v7 += 8;
    }
    while ( v7 != v6 );
    __asm
    {
      vmovq   xmm3, cs:qword_6630
      vandpd  xmm1, xmm0, xmm3
    }
  }
  __asm { vmovsd  [rsp+118h+var_118], xmm0 }
  __asm { vmovapd [rsp+118h+var_108], xmm3 }
  __asm { vmovsd  [rsp+118h+var_110], xmm1 }
  v231 = this;
  v232 = 0;
  v233 = 0;
  v234 = 0;
  GOMP_parallel(Benchmark::verify_sums, &v231, 0, 0);
  __asm
  {
    vmovapd xmm3, [rsp+118h+var_108]
    vmovsd  xmm2, [rsp+118h+var_80]
    vmovsd  xmm1, [rsp+118h+var_110]
    vandpd  xmm8, xmm2, xmm3
    vmovsd  xmm0, [rsp+118h+var_118]
    vmovsd  xmm4, [rsp+118h+var_78]
    vmaxsd  xmm1, xmm8, xmm1
    vmovsd  xmm5, [rsp+118h+var_70]
    vsubsd  xmm2, xmm0, xmm2
    vandpd  xmm7, xmm4, xmm3
    vsubsd  xmm4, xmm0, xmm4
    vmaxsd  xmm1, xmm7, xmm1
    vandpd  xmm6, xmm5, xmm3
    vsubsd  xmm0, xmm0, xmm5
    vandpd  xmm2, xmm2, xmm3
    vandpd  xmm4, xmm4, xmm3
    vmaxsd  xmm1, xmm6, xmm1
    vmulsd  xmm1, xmm1, cs:qword_65D0
    vandpd  xmm5, xmm0, xmm3
    vmovsd  [rsp+118h+var_118], xmm5
    vcomisd xmm1, xmm2
  }
  if ( v12 | v13 )
  {
    __asm { vmovsd  [rsp+118h+var_F8], xmm4 }
    __asm
    {
      vmovsd  [rsp+118h+var_110], xmm1
      vmovsd  qword ptr [rsp+118h+var_108], xmm2
    }
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6056, 26);
    __asm { vmovsd  xmm2, qword ptr [rsp+118h+var_108] }
    __asm { vmovsd  xmm0, xmm2, xmm2 }
    v167 = std::ostream::_M_insert<double>(std::cout, *(double *)&_XMM0);
    std::__ostream_insert<char,std::char_traits<char>>(v167, &unk_6071, 3);
    __asm { vmovsd  xmm1, [rsp+118h+var_110] }
    __asm { vmovsd  xmm0, xmm1, xmm1 }
    __asm { vmovsd  xmm1, [rsp+118h+var_110] }
    v171 = (std::ostream *)std::ostream::_M_insert<double>(v167, *(double *)&_XMM0);
    __asm
    {
      vmovsd  xmm2, qword ptr [rsp+118h+var_108]
      vmovsd  xmm4, [rsp+118h+var_F8]
    }
    v174 = *(_QWORD *)(*(_QWORD *)v171 - 24LL);
    v175 = *(_BYTE **)((char *)v171 + v174 + 240);
    if ( !v175 )
      goto LABEL_69;
    if ( v175[56] )
    {
      v176 = v175[67];
    }
    else
    {
      __asm
      {
        vmovsd  [rsp+118h+var_F8], xmm4
        vmovsd  qword ptr [rsp+118h+var_108], xmm2
        vmovsd  [rsp+118h+var_110], xmm1
      }
      std::ctype<char>::_M_widen_init(*(_QWORD *)((char *)v171 + v174 + 240));
      v176 = 10;
      __asm
      {
        vmovsd  xmm1, [rsp+118h+var_110]
        vmovsd  xmm2, qword ptr [rsp+118h+var_108]
        vmovsd  xmm4, [rsp+118h+var_F8]
      }
      v181 = *(__int64 (__fastcall **)(__int64, unsigned int))(*(_QWORD *)v175 + 48LL);
      if ( v181 != std::ctype<char>::do_widen )
      {
        v182 = ((__int64 (__fastcall *)(_BYTE *, __int64, double, double, double, double, double))v181)(
                 v175,
                 10,
                 *(double *)&_XMM0,
                 *(double *)&_XMM1,
                 *(double *)&_XMM2,
                 *(double *)&_XMM3,
                 *(double *)&_XMM4);
        __asm
        {
          vmovsd  xmm4, [rsp+118h+var_F8]
          vmovsd  xmm2, qword ptr [rsp+118h+var_108]
        }
        v176 = v182;
        __asm { vmovsd  xmm1, [rsp+118h+var_110] }
      }
    }
    __asm
    {
      vmovsd  [rsp+118h+var_F8], xmm4
      vmovsd  qword ptr [rsp+118h+var_108], xmm2
      vmovsd  [rsp+118h+var_110], xmm1
    }
    v177 = (std::ostream *)std::ostream::put(v171, v176);
    std::ostream::flush(v177);
    __asm
    {
      vmovsd  xmm4, [rsp+118h+var_F8]
      vmovsd  xmm2, qword ptr [rsp+118h+var_108]
      vmovsd  xmm1, [rsp+118h+var_110]
    }
  }
  __asm { vcomisd xmm1, xmm4 }
  if ( !(v12 | v13) )
  {
    __asm { vcomisd xmm1, [rsp+118h+var_118] }
    __asm { vcomisd xmm1, xmm2 }
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_60A7, 22);
    v33 = 29;
    v34 = &unk_6038;
    goto LABEL_8;
  }
  __asm { vmovsd  [rsp+118h+var_110], xmm1 }
  __asm { vmovsd  qword ptr [rsp+118h+var_108], xmm4 }
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6075, 23);
  __asm { vmovsd  xmm4, qword ptr [rsp+118h+var_108] }
  __asm { vmovsd  xmm0, xmm4, xmm4 }
  v155 = std::ostream::_M_insert<double>(std::cout, *(double *)&_XMM0);
  std::__ostream_insert<char,std::char_traits<char>>(v155, &unk_6071, 3);
  __asm { vmovsd  xmm1, [rsp+118h+var_110] }
  __asm { vmovsd  xmm0, xmm1, xmm1 }
  v158 = (std::ostream *)std::ostream::_M_insert<double>(v155, *(double *)&_XMM0);
  v159 = *(_QWORD *)(*(_QWORD *)v158 - 24LL);
  v160 = *(_BYTE **)((char *)v158 + v159 + 240);
  if ( !v160 )
    goto LABEL_69;
  __asm { vmovsd  xmm1, [rsp+118h+var_110] }
  if ( v160[56] )
  {
    v162 = v160[67];
  }
  else
  {
    __asm { vmovsd  [rsp+118h+var_110], xmm1 }
    std::ctype<char>::_M_widen_init(*(_QWORD *)((char *)v158 + v159 + 240));
    v162 = 10;
    __asm { vmovsd  xmm1, [rsp+118h+var_110] }
    v178 = *(__int64 (__fastcall **)(__int64, unsigned int))(*(_QWORD *)v160 + 48LL);
    if ( v178 != std::ctype<char>::do_widen )
    {
      v179 = ((__int64 (__fastcall *)(_BYTE *, __int64, double, double, double))v178)(
               v160,
               10,
               *(double *)&_XMM0,
               *(double *)&_XMM1,
               *(double *)&_XMM2);
      __asm { vmovsd  xmm1, [rsp+118h+var_110] }
      v162 = v179;
    }
  }
  __asm { vmovsd  [rsp+118h+var_110], xmm1 }
  v163 = (std::ostream *)std::ostream::put(v158, v162);
  std::ostream::flush(v163);
  __asm
  {
    vmovsd  xmm1, [rsp+118h+var_110]
    vcomisd xmm1, [rsp+118h+var_118]
  }
  if ( !(v12 | v13) )
    goto LABEL_45;
  __asm { vmovsd  [rsp+118h+var_110], xmm1 }
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_608D, 25);
  __asm { vmovsd  xmm0, [rsp+118h+var_118] }
  v93 = std::ostream::_M_insert<double>(std::cout, *(double *)&_XMM0);
  std::__ostream_insert<char,std::char_traits<char>>(v93, &unk_6071, 3);
  __asm { vmovsd  xmm1, [rsp+118h+var_110] }
  __asm { vmovsd  xmm0, xmm1, xmm1 }
  v96 = (std::ostream *)std::ostream::_M_insert<double>(v93, *(double *)&_XMM0);
  v97 = *(_QWORD *)(*(_QWORD *)v96 - 24LL);
  v98 = *(_BYTE **)((char *)v96 + v97 + 240);
  if ( !v98 )
LABEL_69:
    std::__throw_bad_cast();
  if ( v98[56] )
  {
    v99 = v98[67];
  }
  else
  {
    std::ctype<char>::_M_widen_init(*(_QWORD *)((char *)v96 + v97 + 240));
    v99 = 10;
    v180 = *(__int64 (__fastcall **)(__int64, unsigned int))(*(_QWORD *)v98 + 48LL);
    if ( v180 != std::ctype<char>::do_widen )
      v99 = ((__int64 (__fastcall *)(_BYTE *, __int64, double, double, double))v180)(
              v98,
              10,
              *(double *)&_XMM0,
              *(double *)&_XMM1,
              *(double *)&_XMM2);
  }
  v100 = (std::ostream *)std::ostream::put(v96, v99);
  std::ostream::flush(v100);
LABEL_45:
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_60A7, 22);
  v33 = 25;
  v34 = &unk_601E;
LABEL_8:
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, v34, v33);
  v35 = *(_QWORD *)(std::cout[0] - 24LL);
  v36 = *(_BYTE **)((char *)&std::cout[30] + v35);
  if ( !v36 )
    goto LABEL_69;
  if ( v36[56] )
  {
    v37 = v36[67];
  }
  else
  {
    std::ctype<char>::_M_widen_init(*(_QWORD *)((char *)&std::cout[30] + v35));
    v37 = 10;
    v152 = *(__int64 (__fastcall **)(__int64, unsigned int))(*(_QWORD *)v36 + 48LL);
    if ( v152 != std::ctype<char>::do_widen )
      v37 = v152((__int64)v36, 10u);
  }
  v38 = (std::ostream *)std::ostream::put((std::ostream *)std::cout, v37);
  std::ostream::flush(v38);
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_61F0, 57);
  v39 = std::ostream::operator<<(std::cout, 3);
  std::__ostream_insert<char,std::char_traits<char>>(v39, &unk_60BE, 24);
  v231 = 0;
  v232 = 0;
  v233 = 0;
  _RAX = (char *)operator new(0x10u);
  __asm { vmovdqa xmm0, cs:xmmword_6640 }
  v42 = (int *)(_RAX + 16);
  v227 = _RAX;
  v231 = (Benchmark *)_RAX;
  _RAX += 4;
  __asm { vmovdqu xmmword ptr [rax-4], xmm0 }
  v226 = v42;
  v233 = v42;
  v232 = v42;
  v223 = (int *)_RAX;
  for ( i = 1; ; i = v91 )
  {
    omp_set_num_threads((unsigned int)i);
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_60D7, 21);
    v43 = std::ostream::operator<<(std::cout, (unsigned int)i);
    std::__ostream_insert<char,std::char_traits<char>>(v43, " ---\n", 5);
    v235 = v237;
    _RAX = operator new(0x13u);
    __asm { vmovdqa xmm0, cs:xmmword_6650 }
    *(_BYTE *)(_RAX + 18) = 0;
    v46 = 3;
    v235 = (void *)_RAX;
    __asm
    {
      vmovsd  xmm7, [rsp+118h+var_F0]
      vmovdqu xmmword ptr [rax], xmm0
    }
    *(_WORD *)(_RAX + 16) = (unsigned __int16)sub_2020;
    v237[0] = 18;
    v236 = 18;
    __asm { vmovsd  [rsp+118h+var_110], xmm7 }
    __asm { vmovsd  [rsp+118h+var_118], xmm7 }
    do
    {
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)sub_2020);
      v48 = *((_QWORD *)this + 1);
      __asm { vxorpd  xmm0, xmm0, xmm0 }
      for ( j = *(_QWORD *)this; j != v48; j += 8 )
        __asm { vaddsd  xmm0, xmm0, qword ptr [rax] }
      __asm { vmovq   rax, xmm0 }
      __asm { vxorpd  xmm6, xmm6, xmm6 }
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)sub_2020);
      __asm
      {
        vcvtsi2sd xmm0, xmm6, rax
        vdivsd  xmm0, xmm0, cs:qword_65D8
        vaddsd  xmm7, xmm0, [rsp+118h+var_118]
        vminsd  xmm4, xmm0, qword ptr [rsp+118h+var_108]
        vmaxsd  xmm2, xmm0, [rsp+118h+var_110]
        vmovsd  [rsp+118h+var_118], xmm7
        vmovsd  qword ptr [rsp+118h+var_108], xmm4
        vmovsd  [rsp+118h+var_110], xmm2
      }
      --v46;
    }
    while ( v46 );
    __asm
    {
      vdivsd  xmm4, xmm7, cs:qword_65E0
      vmovsd  [rsp+118h+var_D0], xmm4
    }
    v57 = v235;
    if ( v236 )
    {
      v111 = std::__ostream_insert<char,std::char_traits<char>>(std::cout, v235, v236);
      std::__ostream_insert<char,std::char_traits<char>>(v111, &unk_6573, 2);
      __asm { vmovsd  xmm0, [rsp+118h+var_D0] }
      v113 = std::ostream::_M_insert<double>(v111, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v113, &unk_60F3, 14);
      __asm { vmovsd  xmm0, qword ptr [rsp+118h+var_108] }
      v115 = std::ostream::_M_insert<double>(v113, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v115, ", max: ", 7);
      __asm { vmovsd  xmm0, [rsp+118h+var_110] }
      v117 = std::ostream::_M_insert<double>(v115, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v117, ", diff: ", 8);
      __asm { vmovsd  xmm4, [rsp+118h+var_110] }
      __asm { vsubsd  xmm0, xmm4, qword ptr [rsp+118h+var_108] }
      v120 = std::ostream::_M_insert<double>(v117, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v120, &unk_655D, 2);
      v57 = v235;
    }
    if ( v57 != v237 )
      operator delete(v57, v237[0] + 1LL);
    v58 = (signed __int64 (__fastcall *)(signed __int64 *, __m128))((char *)&word_12 + 1);
    v235 = v237;
    _RAX = operator new((unsigned __int64)&word_12 + 1);
    __asm { vmovdqa xmm0, cs:xmmword_6660 }
    *(_BYTE *)(_RAX + 18) = 0;
    v61 = 3;
    v235 = (void *)_RAX;
    __asm { vmovsd  xmm1, [rsp+118h+var_F0] }
    __asm { vmovdqu xmmword ptr [rax], xmm0 }
    *(_WORD *)(_RAX + 16) = 8224;
    v237[0] = 18;
    v236 = 18;
    __asm { vmovsd  [rsp+118h+var_110], xmm1 }
    do
    {
      __asm { vmovsd  qword ptr [rsp+118h+var_108], xmm1 }
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)v58);
      v58 = Benchmark::openmp_reduction_sum;
      v230 = 0;
      v229 = this;
      GOMP_parallel(Benchmark::openmp_reduction_sum, &v229, 0, 0);
      __asm
      {
        vxorpd  xmm7, xmm7, xmm7
        vmovsd  xmm1, qword ptr [rsp+118h+var_108]
      }
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)Benchmark::openmp_reduction_sum);
      __asm
      {
        vcvtsi2sd xmm0, xmm7, rax
        vdivsd  xmm0, xmm0, cs:qword_65D8
        vminsd  xmm5, xmm0, [rsp+118h+var_118]
        vmaxsd  xmm3, xmm0, [rsp+118h+var_110]
        vaddsd  xmm1, xmm1, xmm0
        vmovsd  [rsp+118h+var_118], xmm5
        vmovsd  [rsp+118h+var_110], xmm3
      }
      --v61;
    }
    while ( v61 );
    __asm
    {
      vdivsd  xmm2, xmm1, cs:qword_65E0
      vmovsd  [rsp+118h+var_C8], xmm2
    }
    v69 = v235;
    if ( v236 )
    {
      v121 = std::__ostream_insert<char,std::char_traits<char>>(std::cout, v235, v236);
      std::__ostream_insert<char,std::char_traits<char>>(v121, &unk_6573, 2);
      __asm { vmovsd  xmm0, [rsp+118h+var_C8] }
      v123 = std::ostream::_M_insert<double>(v121, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v123, &unk_60F3, 14);
      __asm { vmovsd  xmm0, [rsp+118h+var_118] }
      v125 = std::ostream::_M_insert<double>(v123, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v125, ", max: ", 7);
      __asm { vmovsd  xmm0, [rsp+118h+var_110] }
      v127 = std::ostream::_M_insert<double>(v125, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v127, ", diff: ", 8);
      __asm { vmovsd  xmm3, [rsp+118h+var_110] }
      __asm { vsubsd  xmm0, xmm3, [rsp+118h+var_118] }
      v130 = std::ostream::_M_insert<double>(v127, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v130, &unk_655D, 2);
      v69 = v235;
    }
    if ( v69 != v237 )
      operator delete(v69, v237[0] + 1LL);
    v70 = (signed __int64 (__fastcall *)(volatile signed __int64 **, __m128))((char *)&word_12 + 1);
    v235 = v237;
    _RAX = (char *)operator new((unsigned __int64)&word_12 + 1);
    __asm { vmovdqa xmm0, cs:xmmword_6670 }
    strcpy(_RAX + 16, "  ");
    v73 = 3;
    __asm { vmovsd  xmm6, [rsp+118h+var_F0] }
    v235 = _RAX;
    __asm { vmovdqu xmmword ptr [rax], xmm0 }
    v237[0] = 18;
    v236 = 18;
    __asm { vmovsd  [rsp+118h+var_118], xmm6 }
    __asm { vmovsd  qword ptr [rsp+118h+var_108], xmm6 }
    do
    {
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)v70);
      v70 = Benchmark::openmp_atomic_sum;
      v228 = 0;
      v229 = this;
      v230 = &v228;
      GOMP_parallel(Benchmark::openmp_atomic_sum, &v229, 0, 0);
      __asm { vxorpd  xmm7, xmm7, xmm7 }
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)Benchmark::openmp_atomic_sum);
      __asm
      {
        vcvtsi2sd xmm0, xmm7, rax
        vdivsd  xmm0, xmm0, cs:qword_65D8
        vaddsd  xmm6, xmm0, qword ptr [rsp+118h+var_108]
        vminsd  xmm4, xmm0, [rsp+118h+var_110]
        vmaxsd  xmm2, xmm0, [rsp+118h+var_118]
        vmovsd  qword ptr [rsp+118h+var_108], xmm6
        vmovsd  [rsp+118h+var_110], xmm4
        vmovsd  [rsp+118h+var_118], xmm2
      }
      --v73;
    }
    while ( v73 );
    v80 = v235;
    if ( v236 )
    {
      v131 = std::__ostream_insert<char,std::char_traits<char>>(std::cout, v235, v236);
      std::__ostream_insert<char,std::char_traits<char>>(v131, &unk_6573, 2);
      __asm
      {
        vmovsd  xmm2, qword ptr [rsp+118h+var_108]
        vdivsd  xmm0, xmm2, cs:qword_65E0
      }
      v134 = std::ostream::_M_insert<double>(v131, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v134, &unk_60F3, 14);
      __asm { vmovsd  xmm0, [rsp+118h+var_110] }
      v136 = std::ostream::_M_insert<double>(v134, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v136, ", max: ", 7);
      __asm { vmovsd  xmm0, [rsp+118h+var_118] }
      v138 = std::ostream::_M_insert<double>(v136, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v138, ", diff: ", 8);
      __asm { vmovsd  xmm3, [rsp+118h+var_118] }
      __asm { vsubsd  xmm0, xmm3, [rsp+118h+var_110] }
      v141 = std::ostream::_M_insert<double>(v138, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v141, &unk_655D, 2);
      v80 = v235;
    }
    if ( v80 != v237 )
      operator delete(v80, v237[0] + 1LL);
    v81 = (__int64 (__fastcall *)(__int64 **, __m128))((char *)&word_12 + 1);
    v235 = v237;
    _RAX = operator new((unsigned __int64)&word_12 + 1);
    __asm { vmovdqa xmm0, cs:xmmword_6680 }
    *(_BYTE *)(_RAX + 18) = 0;
    v84 = 3;
    v235 = (void *)_RAX;
    __asm { vmovsd  xmm5, [rsp+118h+var_F0] }
    __asm { vmovdqu xmmword ptr [rax], xmm0 }
    *(_WORD *)(_RAX + 16) = 8224;
    v237[0] = 18;
    v236 = 18;
    __asm { vmovsd  [rsp+118h+var_110], xmm5 }
    __asm { vmovsd  qword ptr [rsp+118h+var_108], xmm5 }
    do
    {
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)v81);
      v81 = Benchmark::openmp_critical_sum;
      v229 = this;
      v230 = 0;
      GOMP_parallel(Benchmark::openmp_critical_sum, &v229, 0, 0);
      __asm { vxorpd  xmm7, xmm7, xmm7 }
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)Benchmark::openmp_critical_sum);
      __asm
      {
        vcvtsi2sd xmm0, xmm7, rax
        vdivsd  xmm0, xmm0, cs:qword_65D8
        vaddsd  xmm6, xmm0, qword ptr [rsp+118h+var_108]
        vminsd  xmm4, xmm0, [rsp+118h+var_118]
        vmaxsd  xmm2, xmm0, [rsp+118h+var_110]
        vmovsd  qword ptr [rsp+118h+var_108], xmm6
        vmovsd  [rsp+118h+var_118], xmm4
        vmovsd  [rsp+118h+var_110], xmm2
      }
      --v84;
    }
    while ( v84 );
    v90 = v235;
    if ( v236 )
    {
      v142 = std::__ostream_insert<char,std::char_traits<char>>(std::cout, v235, v236);
      std::__ostream_insert<char,std::char_traits<char>>(v142, &unk_6573, 2);
      __asm
      {
        vmovsd  xmm6, qword ptr [rsp+118h+var_108]
        vdivsd  xmm0, xmm6, cs:qword_65E0
      }
      v144 = std::ostream::_M_insert<double>(v142, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v144, &unk_60F3, 14);
      __asm { vmovsd  xmm0, [rsp+118h+var_118] }
      v146 = std::ostream::_M_insert<double>(v144, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v146, ", max: ", 7);
      __asm { vmovsd  xmm0, [rsp+118h+var_110] }
      v148 = std::ostream::_M_insert<double>(v146, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v148, ", diff: ", 8);
      __asm { vmovsd  xmm3, [rsp+118h+var_110] }
      __asm { vsubsd  xmm0, xmm3, [rsp+118h+var_118] }
      v151 = std::ostream::_M_insert<double>(v148, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v151, &unk_655D, 2);
      v90 = v235;
    }
    if ( v90 != v237 )
      operator delete(v90, v237[0] + 1LL);
    if ( i > 1 )
      break;
    if ( v223 == v226 )
      goto LABEL_49;
LABEL_40:
    v91 = *v223++;
  }
  __asm
  {
    vmovsd  xmm3, [rsp+118h+var_D0]
    vdivsd  xmm2, xmm3, [rsp+118h+var_C8]
  }
  __asm { vmovq   rbp, xmm2 }
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6230, 30);
  __asm { vmovq   xmm0, rbp }
  v105 = std::ostream::_M_insert<double>(std::cout, *(double *)&_XMM0);
  std::__ostream_insert<char,std::char_traits<char>>(v105, "x (", 3);
  __asm
  {
    vxorpd  xmm2, xmm2, xmm2
    vcvtsi2sd xmm0, xmm2, r14d
    vmovq   xmm3, rbp
    vmulsd  xmm1, xmm0, cs:qword_65E8
    vcomisd xmm3, xmm1
  }
  if ( v12 | v13 )
  {
    __asm
    {
      vmulsd  xmm0, xmm0, cs:qword_65F0
      vcomisd xmm3, xmm0
    }
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6133, 10);
  }
  else
  {
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6117, 14);
  }
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_655D, 2);
  if ( v223 != v226 )
    goto LABEL_40;
LABEL_49:
  operator delete(v227, 0x10u);
}
// 3613: variable 'v12' is possibly undefined
// 3613: variable 'v13' is possibly undefined
// 12: using guessed type __int16 word_12;
// 2350: using guessed type __int64 __fastcall omp_set_num_threads(_QWORD);
// 2360: using guessed type __int64 __fastcall std::__ostream_insert<char,std::char_traits<char>>(_QWORD, _QWORD, _QWORD);
// 2370: using guessed type __int64 __fastcall std::ctype<char>::_M_widen_init(_QWORD);
// 23A0: using guessed type __int64 __fastcall GOMP_parallel(_QWORD, _QWORD, _QWORD, _QWORD);
// 23D0: using guessed type __int64 __fastcall std::ostream::_M_insert<double>(_QWORD, double);
// 2420: using guessed type __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 9040: using guessed type _QWORD std::cout[36];

//----- (00000000000044A0) ----------------------------------------------------
void __fastcall Benchmark::run_vectorization_benchmark(
        Benchmark *this,
        double a2,
        double a3,
        __m128 _XMM2,
        __m128 _XMM3)
{
  __int64 v6; // rsi
  __int64 v7; // rsi
  __int64 v8; // rsi
  unsigned __int64 v10; // rax
  bool v11; // cc
  __int64 v17; // rbp
  __int64 v20; // rbp
  std::ostream *v23; // rbp
  __int64 v24; // rax
  _BYTE *v25; // r13
  char v26; // si
  std::ostream *v27; // rax
  __int64 v28; // rax
  Benchmark *v30; // rcx
  unsigned int v31; // ebp
  __int64 v33; // rax
  unsigned __int64 (__fastcall *v34)(__int64 **); // rdi
  int v37; // r15d
  __int64 v38; // rsi
  _QWORD *v44; // rdi
  unsigned __int64 (__fastcall *v45)(__int64 **, __m128); // rdi
  int v48; // r15d
  __int64 v50; // rsi
  _QWORD *v57; // rdi
  __int64 v62; // rax
  char v63; // cf
  char v65; // zf
  __int64 v66; // rax
  _BYTE *v67; // rbp
  char v68; // si
  std::ostream *v69; // rax
  __int64 v70; // rax
  _BYTE *v71; // rbp
  char v72; // si
  __int64 (__fastcall *v73)(__int64, unsigned int); // rax
  __int64 (__fastcall *v74)(__int64, unsigned int); // rax
  __int64 v75; // rbp
  __int64 v77; // rbp
  __int64 v79; // rbp
  __int64 v81; // rbp
  __int64 v84; // rax
  __int64 v85; // rbp
  __int64 v87; // rbp
  __int64 v89; // rbp
  __int64 v91; // rbp
  __int64 v94; // rax
  __int64 (__fastcall *v95)(__int64, unsigned int); // rax
  unsigned int *i; // [rsp+38h] [rbp-100h]
  unsigned int *v105; // [rsp+48h] [rbp-F0h]
  void *v106; // [rsp+58h] [rbp-E0h]
  void **v107; // [rsp+60h] [rbp-D8h] BYREF
  Benchmark *v108; // [rsp+68h] [rbp-D0h]
  void **v109; // [rsp+70h] [rbp-C8h] BYREF
  Benchmark *v110; // [rsp+78h] [rbp-C0h]
  Benchmark *v111; // [rsp+80h] [rbp-B8h]
  void *v112; // [rsp+90h] [rbp-A8h] BYREF
  char *v113; // [rsp+98h] [rbp-A0h]
  __int64 v114; // [rsp+A0h] [rbp-98h]
  void *v115; // [rsp+B0h] [rbp-88h] BYREF
  char *v116; // [rsp+B8h] [rbp-80h]
  __int64 v117; // [rsp+C0h] [rbp-78h]
  void *v118; // [rsp+D0h] [rbp-68h]
  __int64 v119; // [rsp+D8h] [rbp-60h]
  _QWORD v120[11]; // [rsp+E0h] [rbp-58h] BYREF

  v120[3] = __readfsqword(0x28u);
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6250, 49);
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, "==========================\n", 27);
  v6 = *((_QWORD *)this + 4);
  v112 = 0;
  v113 = 0;
  v114 = 0;
  v115 = 0;
  v116 = 0;
  v117 = 0;
  v7 = v6 - *((_QWORD *)this + 3);
  if ( v7 )
    std::vector<float>::_M_default_append((__int64)&v112, v7 >> 2);
  v110 = this;
  v109 = &v112;
  GOMP_parallel(Benchmark::standard_vector_operation, &v109, 0, 0);
  v8 = *((_QWORD *)this + 4) - *((_QWORD *)this + 3);
  if ( v116 - (_BYTE *)v115 < (unsigned __int64)v8 )
  {
    std::vector<float>::_M_default_append((__int64)&v115, (v8 >> 2) - ((v116 - (_BYTE *)v115) >> 2));
  }
  else if ( v116 - (_BYTE *)v115 > (unsigned __int64)v8 && v116 != (char *)v115 + v8 )
  {
    v116 = (char *)v115 + v8;
  }
  v110 = this;
  v109 = &v115;
  GOMP_parallel(Benchmark::vectorized_operation, &v109, 0, 0);
  _RDX = v112;
  v10 = (v113 - (_BYTE *)v112) >> 2;
  if ( v10 )
  {
    v11 = 1;
    _RBP = 0;
    __asm { vmovss  xmm1, cs:dword_6690 }
    while ( 1 )
    {
      __asm { vmovss  xmm0, dword ptr [rdx+rbp*4] }
      __asm
      {
        vsubss  xmm0, xmm0, dword ptr [rcx+rbp*4]
        vandps  xmm0, xmm0, xmm1
        vcomiss xmm0, cs:dword_66D0
      }
      if ( !v11 )
        break;
      _RBP += 1000000LL;
      v11 = _RBP <= v10;
      if ( _RBP >= v10 )
        goto LABEL_46;
    }
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6288, 62);
    v17 = std::ostream::_M_insert<unsigned long>(std::cout, _RBP, *(double *)&_XMM0, *(double *)&_XMM1);
    std::__ostream_insert<char,std::char_traits<char>>(v17, &unk_6573, 2);
    __asm
    {
      vxorpd  xmm3, xmm3, xmm3
      vcvtss2sd xmm0, xmm3, dword ptr [rax+r13]
    }
    v20 = std::ostream::_M_insert<double>(v17, *(double *)&_XMM0);
    std::__ostream_insert<char,std::char_traits<char>>(v20, " != ", 4);
    __asm
    {
      vxorpd  xmm3, xmm3, xmm3
      vcvtss2sd xmm0, xmm3, dword ptr [rax+r13]
    }
    v23 = (std::ostream *)std::ostream::_M_insert<double>(v20, *(double *)&_XMM0);
    v24 = *(_QWORD *)(*(_QWORD *)v23 - 24LL);
    v25 = *(_BYTE **)((char *)v23 + v24 + 240);
    if ( !v25 )
      std::__throw_bad_cast();
    if ( v25[56] )
    {
      v26 = v25[67];
    }
    else
    {
      std::ctype<char>::_M_widen_init(*(_QWORD *)((char *)v23 + v24 + 240));
      v26 = 10;
      v95 = *(__int64 (__fastcall **)(__int64, unsigned int))(*(_QWORD *)v25 + 48LL);
      if ( v95 != std::ctype<char>::do_widen )
        v26 = v95((__int64)v25, 10u);
    }
    v27 = (std::ostream *)std::ostream::put(v23, v26);
  }
  else
  {
LABEL_46:
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_62C8, 50);
    v70 = *(_QWORD *)(std::cout[0] - 24LL);
    v71 = *(_BYTE **)((char *)&std::cout[30] + v70);
    if ( !v71 )
      std::__throw_bad_cast();
    if ( v71[56] )
    {
      v72 = v71[67];
    }
    else
    {
      std::ctype<char>::_M_widen_init(*(_QWORD *)((char *)&std::cout[30] + v70));
      v72 = 10;
      v73 = *(__int64 (__fastcall **)(__int64, unsigned int))(*(_QWORD *)v71 + 48LL);
      if ( v73 != std::ctype<char>::do_widen )
        v72 = v73((__int64)v71, 10u);
    }
    v27 = (std::ostream *)std::ostream::put((std::ostream *)std::cout, v72);
  }
  std::ostream::flush(v27);
  if ( v115 )
    operator delete(v115, v117 - (_QWORD)v115);
  if ( v112 )
    operator delete(v112, v114 - (_QWORD)v112);
  std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_61F0, 57);
  v28 = std::ostream::operator<<(std::cout, 3);
  std::__ostream_insert<char,std::char_traits<char>>(v28, &unk_60BE, 24);
  v109 = 0;
  v110 = 0;
  v111 = 0;
  _RAX = (char *)operator new(0x10u);
  v30 = (Benchmark *)(_RAX + 16);
  v106 = _RAX;
  v31 = 1;
  __asm { vmovdqa xmm0, cs:xmmword_6640 }
  v109 = (void **)_RAX;
  _RAX += 4;
  __asm { vmovdqu xmmword ptr [rax-4], xmm0 }
  v105 = (unsigned int *)v30;
  v111 = v30;
  v110 = v30;
  v112 = 0;
  v113 = 0;
  v114 = 0;
  v115 = 0;
  v116 = 0;
  v117 = 0;
  for ( i = (unsigned int *)_RAX; ; ++i )
  {
    omp_set_num_threads(v31);
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_60D7, 21);
    v33 = std::ostream::operator<<(std::cout, v31);
    std::__ostream_insert<char,std::char_traits<char>>(v33, " ---\n", 5);
    v34 = (unsigned __int64 (__fastcall *)(__int64 **))((char *)&off_18 + 5);
    v118 = v120;
    _RAX = operator new((unsigned __int64)&off_18 + 5);
    __asm { vmovdqa xmm0, cs:xmmword_66A0 }
    v118 = (void *)_RAX;
    v37 = 3;
    *(_QWORD *)(_RAX + 16) = 0x20208FD1B0D0BDD0LL;
    __asm { vmovdqu xmmword ptr [rax], xmm0 }
    strcpy((char *)(_RAX + 24), "    ");
    v120[0] = 28;
    v119 = 28;
    do
    {
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)v34);
      v38 = *((_QWORD *)this + 4) - *((_QWORD *)this + 3);
      if ( v113 - (_BYTE *)v112 < (unsigned __int64)v38 )
      {
        std::vector<float>::_M_default_append((__int64)&v112, (v38 >> 2) - ((v113 - (_BYTE *)v112) >> 2));
      }
      else if ( v113 - (_BYTE *)v112 > (unsigned __int64)v38 && v113 != (char *)v112 + v38 )
      {
        v113 = (char *)v112 + v38;
      }
      v34 = Benchmark::standard_vector_operation;
      v108 = this;
      v107 = &v112;
      GOMP_parallel(Benchmark::standard_vector_operation, &v107, 0, 0);
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)Benchmark::standard_vector_operation);
      __asm { vxorpd  xmm2, xmm2, xmm2 }
      __asm
      {
        vcvtsi2sd xmm0, xmm2, rax
        vdivsd  xmm0, xmm0, cs:qword_65D8
        vaddsd  xmm3, xmm0, [rsp+138h+var_130]
        vminsd  xmm5, xmm0, [rsp+138h+var_120]
        vmaxsd  xmm7, xmm0, [rsp+138h+var_128]
        vmovsd  [rsp+138h+var_130], xmm3
        vmovsd  [rsp+138h+var_120], xmm5
        vmovsd  [rsp+138h+var_128], xmm7
      }
      --v37;
    }
    while ( v37 );
    __asm
    {
      vdivsd  xmm2, xmm3, cs:qword_65E0
      vmovsd  [rsp+138h+var_F8], xmm2
    }
    v44 = v118;
    if ( v119 )
    {
      v75 = std::__ostream_insert<char,std::char_traits<char>>(std::cout, v118, v119);
      std::__ostream_insert<char,std::char_traits<char>>(v75, &unk_6573, 2);
      __asm { vmovsd  xmm0, [rsp+138h+var_F8] }
      v77 = std::ostream::_M_insert<double>(v75, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v77, &unk_60F3, 14);
      __asm { vmovsd  xmm0, [rsp+138h+var_120] }
      v79 = std::ostream::_M_insert<double>(v77, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v79, ", max: ", 7);
      __asm { vmovsd  xmm0, [rsp+138h+var_128] }
      v81 = std::ostream::_M_insert<double>(v79, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v81, ", diff: ", 8);
      __asm { vmovsd  xmm7, [rsp+138h+var_128] }
      __asm { vsubsd  xmm0, xmm7, [rsp+138h+var_120] }
      v84 = std::ostream::_M_insert<double>(v81, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v84, &unk_655D, 2);
      v44 = v118;
    }
    if ( v44 != v120 )
      operator delete(v44, v120[0] + 1LL);
    v45 = (unsigned __int64 (__fastcall *)(__int64 **, __m128))((char *)&qword_20 + 1);
    v118 = v120;
    _RAX = (_BYTE *)operator new((unsigned __int64)&qword_20 + 1);
    __asm { vmovdqa xmm0, cs:xmmword_66B0 }
    _RAX[32] = 0;
    v48 = 3;
    v118 = _RAX;
    __asm
    {
      vmovdqu xmmword ptr [rax], xmm0
      vmovdqa xmm0, cs:xmmword_66C0
    }
    v120[0] = 32;
    __asm { vmovdqu xmmword ptr [rax+10h], xmm0 }
    v119 = 32;
    do
    {
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)v45);
      v50 = *((_QWORD *)this + 4) - *((_QWORD *)this + 3);
      if ( v50 > (unsigned __int64)(v116 - (_BYTE *)v115) )
      {
        std::vector<float>::_M_default_append((__int64)&v115, (v50 >> 2) - ((v116 - (_BYTE *)v115) >> 2));
      }
      else if ( v50 < (unsigned __int64)(v116 - (_BYTE *)v115) && v116 != (char *)v115 + v50 )
      {
        v116 = (char *)v115 + v50;
      }
      v45 = Benchmark::vectorized_operation;
      v108 = this;
      v107 = &v115;
      GOMP_parallel(Benchmark::vectorized_operation, &v107, 0, 0);
      std::chrono::_V2::system_clock::now((std::chrono::_V2::system_clock *)Benchmark::vectorized_operation);
      __asm { vxorpd  xmm2, xmm2, xmm2 }
      __asm
      {
        vcvtsi2sd xmm0, xmm2, rax
        vdivsd  xmm0, xmm0, cs:qword_65D8
        vaddsd  xmm3, xmm0, [rsp+138h+var_130]
        vminsd  xmm5, xmm0, [rsp+138h+var_128]
        vmaxsd  xmm7, xmm0, [rsp+138h+var_120]
        vmovsd  [rsp+138h+var_130], xmm3
        vmovsd  [rsp+138h+var_128], xmm5
        vmovsd  [rsp+138h+var_120], xmm7
      }
      --v48;
    }
    while ( v48 );
    __asm
    {
      vdivsd  xmm4, xmm3, cs:qword_65E0
      vmovsd  [rsp+138h+var_130], xmm4
    }
    v57 = v118;
    if ( v119 )
    {
      v85 = std::__ostream_insert<char,std::char_traits<char>>(std::cout, v118, v119);
      std::__ostream_insert<char,std::char_traits<char>>(v85, &unk_6573, 2);
      __asm { vmovsd  xmm0, [rsp+138h+var_130] }
      v87 = std::ostream::_M_insert<double>(v85, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v87, &unk_60F3, 14);
      __asm { vmovsd  xmm0, [rsp+138h+var_128] }
      v89 = std::ostream::_M_insert<double>(v87, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v89, ", max: ", 7);
      __asm { vmovsd  xmm0, [rsp+138h+var_120] }
      v91 = std::ostream::_M_insert<double>(v89, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v91, ", diff: ", 8);
      __asm { vmovsd  xmm3, [rsp+138h+var_120] }
      __asm { vsubsd  xmm0, xmm3, [rsp+138h+var_128] }
      v94 = std::ostream::_M_insert<double>(v91, *(double *)&_XMM0);
      std::__ostream_insert<char,std::char_traits<char>>(v94, &unk_655D, 2);
      v57 = v118;
    }
    if ( v57 != v120 )
      operator delete(v57, v120[0] + 1LL);
    __asm
    {
      vmovsd  xmm7, [rsp+138h+var_F8]
      vdivsd  xmm6, xmm7, [rsp+138h+var_130]
    }
    __asm { vmovq   rbp, xmm6 }
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6376, 20);
    __asm { vmovq   xmm0, rbp }
    v62 = std::ostream::_M_insert<double>(std::cout, *(double *)&_XMM0);
    std::__ostream_insert<char,std::char_traits<char>>(v62, "x - ", 4);
    __asm
    {
      vmovq   xmm5, rbp
      vcomisd xmm5, cs:qword_65F8
    }
    if ( v63 | v65 )
    {
      __asm { vcomisd xmm5, cs:qword_6600 }
      __asm { vcomisd xmm5, cs:qword_6608 }
      if ( v63 )
        std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_63AE, 24);
      else
        std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6390, 29);
    }
    else
    {
      std::__ostream_insert<char,std::char_traits<char>>(std::cout, &unk_6300, 39);
    }
    v66 = *(_QWORD *)(std::cout[0] - 24LL);
    v67 = *(_BYTE **)((char *)&std::cout[30] + v66);
    if ( !v67 )
      std::__throw_bad_cast();
    if ( v67[56] )
    {
      v68 = v67[67];
    }
    else
    {
      std::ctype<char>::_M_widen_init(*(_QWORD *)((char *)&std::cout[30] + v66));
      v68 = 10;
      v74 = *(__int64 (__fastcall **)(__int64, unsigned int))(*(_QWORD *)v67 + 48LL);
      if ( v74 != std::ctype<char>::do_widen )
        v68 = v74((__int64)v67, 10u);
    }
    v69 = (std::ostream *)std::ostream::put((std::ostream *)std::cout, v68);
    std::ostream::flush(v69);
    if ( v105 == i )
      break;
    v31 = *i;
  }
  if ( v115 )
    operator delete(v115, v117 - (_QWORD)v115);
  if ( v112 )
    operator delete(v112, v114 - (_QWORD)v112);
  operator delete(v106, 0x10u);
}
// 4B93: variable 'v63' is possibly undefined
// 4B93: variable 'v65' is possibly undefined
// 18: using guessed type _UNKNOWN *off_18;
// 20: using guessed type __int64 qword_20;
// 22B0: using guessed type __int64 __fastcall std::ostream::_M_insert<unsigned long>(_QWORD, _QWORD, double, double);
// 2350: using guessed type __int64 __fastcall omp_set_num_threads(_QWORD);
// 2360: using guessed type __int64 __fastcall std::__ostream_insert<char,std::char_traits<char>>(_QWORD, _QWORD, _QWORD);
// 2370: using guessed type __int64 __fastcall std::ctype<char>::_M_widen_init(_QWORD);
// 23A0: using guessed type __int64 __fastcall GOMP_parallel(_QWORD, _QWORD, _QWORD, _QWORD);
// 23D0: using guessed type __int64 __fastcall std::ostream::_M_insert<double>(_QWORD, double);
// 2420: using guessed type __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 9040: using guessed type _QWORD std::cout[36];

//----- (00000000000050E0) ----------------------------------------------------
unsigned __int64 __fastcall std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::_M_gen_rand(
        _QWORD *a1)
{
  _QWORD *v2; // rax
  unsigned __int64 *v3; // rdi
  unsigned __int64 *v4; // rdx
  unsigned __int64 v5; // rsi
  unsigned __int64 v6; // rcx
  unsigned __int64 result; // rax
  unsigned __int64 v8; // rdx

  v2 = a1;
  v3 = a1 + 227;
  v4 = a1;
  do
  {
    v5 = v4[397] ^ ((v4[1] & 0x7FFFFFFF | *v4 & 0xFFFFFFFF80000000LL) >> 1);
    if ( (v4[1] & 1) != 0 )
      v5 ^= 0x9908B0DF;
    *v4++ = v5;
  }
  while ( v3 != v4 );
  do
  {
    v6 = *v2 ^ ((v2[228] & 0x7FFFFFFFLL | v2[227] & 0xFFFFFFFF80000000LL) >> 1);
    if ( (v2[228] & 1) != 0 )
      v6 ^= 0x9908B0DF;
    v2[227] = v6;
    ++v2;
  }
  while ( a1 + 396 != v2 );
  result = *a1 & 0x7FFFFFFFLL | a1[623] & 0xFFFFFFFF80000000LL;
  v8 = a1[396] ^ (result >> 1);
  if ( (*(_BYTE *)a1 & 1) != 0 )
  {
    result = 2567483615LL;
    v8 ^= 0x9908B0DF;
  }
  a1[623] = v8;
  a1[624] = 0;
  return result;
}

//----- (00000000000051D0) ----------------------------------------------------
unsigned __int64 __fastcall std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::operator()(
        _QWORD *a1)
{
  unsigned __int64 v1; // rax
  unsigned __int64 v2; // rdx
  unsigned __int64 v3; // rax
  __int64 v4; // rax

  v1 = a1[624];
  if ( v1 > 0x26F )
  {
    std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::_M_gen_rand(a1);
    v1 = a1[624];
  }
  v2 = v1 + 1;
  v3 = a1[v1];
  a1[624] = v2;
  v4 = v3 ^ (unsigned int)(v3 >> 11) ^ (((unsigned int)v3 ^ (unsigned int)(v3 >> 11)) << 7) & 0x9D2C5680;
  return v4 ^ ((_DWORD)v4 << 15) & 0xEFC60000 ^ ((v4 ^ (unsigned __int64)(((_DWORD)v4 << 15) & 0xEFC60000)) >> 18);
}

//----- (0000000000005240) ----------------------------------------------------
__int64 __fastcall Benchmark::initialize_data(
        __int64 **a1,
        double a2,
        double a3,
        double a4,
        __m128 _XMM3,
        double a6,
        double a7,
        __m128 _XMM6,
        __m128 _XMM7)
{
  __int64 *v9; // r14
  unsigned __int64 v11; // rbp
  unsigned __int64 v12; // rbx
  unsigned __int64 v13; // rcx
  unsigned __int64 v14; // rdx
  unsigned __int64 v15; // rbp
  unsigned __int64 v17; // rbp
  __int64 **v18; // r13
  unsigned __int64 v38; // rbx
  unsigned __int64 num_threads; // rbp
  unsigned __int64 thread_num; // rcx
  unsigned __int64 v41; // rdx
  unsigned __int64 v42; // rbx
  __int64 **v44; // rbp
  unsigned __int64 v84; // [rsp+0h] [rbp-48h]
  __int64 **v85; // [rsp+8h] [rbp-40h]

  v9 = *a1;
  v85 = a1;
  _R15 = **a1;
  v11 = (v9[1] - *v9) >> 3;
  if ( v11 )
  {
    v12 = (int)((__int64 (*)(void))omp_get_num_threads)();
    v13 = (int)((__int64 (*)(void))omp_get_thread_num)();
    v14 = v11 % v12;
    v15 = v11 / v12;
    if ( v13 < v14 )
    {
      ++v15;
      v14 = 0;
    }
    _RBX = v15 * v13 + v14;
    v17 = _RBX + v15;
    if ( _RBX < v17 )
    {
      v18 = (__int64 **)a1[1];
      _R12 = a1[2];
      do
      {
        if ( (std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::operator()(v18)
            & 0x8000000000000000LL) == 0LL )
        {
          __asm
          {
            vxorpd  xmm6, xmm6, xmm6
            vcvtsi2sd xmm0, xmm6, rax
          }
        }
        else
        {
          __asm { vxorpd  xmm6, xmm6, xmm6 }
          __asm
          {
            vcvtsi2sd xmm0, xmm6, rdx
            vaddsd  xmm0, xmm0, xmm0
          }
        }
        __asm
        {
          vxorpd  xmm5, xmm5, xmm5
          vaddsd  xmm4, xmm0, xmm5
        }
        a1 = v18;
        __asm { vmovsd  [rsp+48h+var_48], xmm4 }
        if ( (std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::operator()(v18)
            & 0x8000000000000000LL) != 0LL )
        {
          __asm { vxorpd  xmm7, xmm7, xmm7 }
          __asm
          {
            vcvtsi2sd xmm0, xmm7, rdx
            vaddsd  xmm0, xmm0, xmm0
          }
        }
        else
        {
          __asm
          {
            vxorpd  xmm7, xmm7, xmm7
            vcvtsi2sd xmm0, xmm7, rax
          }
        }
        __asm
        {
          vmulsd  xmm0, xmm0, cs:qword_6618
          vaddsd  xmm0, xmm0, [rsp+48h+var_48]
          vmulsd  xmm0, xmm0, cs:qword_6620
          vmovsd  xmm7, cs:qword_6628
          vmovsd  xmm3, cs:qword_6610
          vmovsd  xmm2, qword ptr [r12]
          vcmplesd xmm1, xmm7, xmm0
          vblendvpd xmm0, xmm0, xmm3, xmm1
          vmovsd  xmm1, qword ptr [r12+8]
          vsubsd  xmm1, xmm1, xmm2
          vmulsd  xmm0, xmm1, xmm0
          vaddsd  xmm0, xmm0, xmm2
          vmovsd  qword ptr [r15+rbx*8], xmm0
        }
        ++_RBX;
      }
      while ( v17 > _RBX );
    }
  }
  GOMP_barrier(a1);
  _R12 = v9[3];
  v38 = (v9[4] - _R12) >> 2;
  if ( v38 )
  {
    num_threads = (int)omp_get_num_threads(a1);
    thread_num = (int)omp_get_thread_num(a1);
    v41 = v38 % num_threads;
    v42 = v38 / num_threads;
    if ( thread_num < v41 )
    {
      ++v42;
      v41 = 0;
    }
    _R13 = v42 * thread_num + v41;
    v84 = v42 + _R13;
    if ( _R13 < v42 + _R13 )
    {
      v44 = (__int64 **)v85[1];
      _R15 = v85[3];
      do
      {
        if ( (std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::operator()(v44)
            & 0x8000000000000000LL) == 0LL )
        {
          __asm
          {
            vxorps  xmm4, xmm4, xmm4
            vcvtsi2ss xmm0, xmm4, rax
          }
        }
        else
        {
          __asm { vxorps  xmm4, xmm4, xmm4 }
          __asm
          {
            vcvtsi2ss xmm0, xmm4, rdx
            vaddss  xmm0, xmm0, xmm0
          }
        }
        __asm
        {
          vxorps  xmm3, xmm3, xmm3
          vaddss  xmm0, xmm0, xmm3
          vmovss  xmm2, dword ptr [r15]
        }
        a1 = v44;
        __asm { vmovss  xmm4, dword ptr cs:ymmword_65A0 }
        _RBX = 4 * _R13;
        __asm
        {
          vmulss  xmm0, xmm0, cs:dword_66D8
          vmovss  xmm5, cs:dword_66D4
          vcmpless xmm1, xmm4, xmm0
          vblendvps xmm0, xmm0, xmm5, xmm1
          vmovss  xmm1, dword ptr [r15+4]
          vsubss  xmm1, xmm1, xmm2
          vmulss  xmm0, xmm1, xmm0
          vaddss  xmm0, xmm0, xmm2
          vmovss  dword ptr [r12+r13*4], xmm0
        }
        if ( (std::mersenne_twister_engine<unsigned long,32ul,624ul,397ul,31ul,2567483615ul,11ul,4294967295ul,7ul,2636928640ul,15ul,4022730752ul,18ul,1812433253ul>::operator()(v44)
            & 0x8000000000000000LL) != 0LL )
        {
          __asm { vxorps  xmm5, xmm5, xmm5 }
          __asm
          {
            vcvtsi2ss xmm0, xmm5, rcx
            vaddss  xmm0, xmm0, xmm0
          }
        }
        else
        {
          __asm
          {
            vxorps  xmm5, xmm5, xmm5
            vcvtsi2ss xmm0, xmm5, rax
          }
        }
        __asm
        {
          vxorps  xmm6, xmm6, xmm6
          vaddss  xmm0, xmm0, xmm6
          vmovss  xmm2, dword ptr [r15]
        }
        ++_R13;
        __asm
        {
          vmulss  xmm0, xmm0, cs:dword_66D8
          vmovss  xmm7, dword ptr cs:ymmword_65A0
          vmovss  xmm3, cs:dword_66D4
        }
        _RAX = v9[6];
        __asm
        {
          vcmpless xmm1, xmm7, xmm0
          vblendvps xmm0, xmm0, xmm3, xmm1
          vmovss  xmm1, dword ptr [r15+4]
          vsubss  xmm1, xmm1, xmm2
          vmulss  xmm0, xmm1, xmm0
          vaddss  xmm0, xmm0, xmm2
          vmovss  dword ptr [rax+rbx], xmm0
        }
      }
      while ( v84 > _R13 );
    }
  }
  return GOMP_barrier(a1);
}
// 23C0: using guessed type __int64 __fastcall omp_get_thread_num(_QWORD);
// 2440: using guessed type __int64 __fastcall GOMP_barrier(_QWORD);
// 2450: using guessed type __int64 __fastcall omp_get_num_threads(_QWORD);

//----- (000000000000556C) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=134 queued=63 decompiled=63 lumina nreq=0 worse=0 better=0
// ALL OK, 63 function(s) have been successfully decompiled
